server:
  port: 1000

spring:
  application:
    name: product
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
    driver-class-name: org.h2.Driver
#    data: classpath:data/user.sql, classpath:data/travel.sql, classpath:data/currency.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create # create-drop # create / create-drop / validate
    show-sql: true
#      generate-ddl: false
    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000 # default 1000

order:
  ribbon:
      MaxAutoRetries: 0
      MaxAutoRetriesNextServer: 1 # 실패시 다른 서버로 재시도하는 횟수

eureka:
  instance:
    prefer-ip-address: true # OS에서 제공하는 hostname 대신 자신의 ip address를 사용 (local 용)
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka